### ISSUE TITLE
Unable to read "bin" directory of module "@datastax/astra-db-ts"

### ISSUE THREAD

**Issue by nicoloboschi** [datastax/astra-db-ts#19]
When running yarn install of an application that depends on it, it throws this warning
```
warning @datastax/astra-db-ts@0.1.4: Unable to read "bin" directory of module "@datastax/astra-db-ts"
```

**Comment by toptobes** [comment]
Not an issue in the v1.0.0 release of the client... if it's just a warning, it shouldn't be a big deal to not fix the `0.x.x` release
