### ISSUE TITLE
Error: Command "deleteMany" failed with the following error: More records found to be deleted even after deleting 20 records

### ISSUE THREAD

**Issue by Gr33nLight** [datastax/astra-db-ts#23]
Hello, 
We are using a metadata key to partition vectors in a collection for multi-tenancy. 
In the delete operation we run the following code: 
```

const astraClient = new AstraDB(
    process.env.ASTRA_DB_APPLICATION_TOKEN,
    process.env.ASTRA_DB_ENDPOINT
  );
  const collection: Collection = await astraClient.collection(collectionName);
  return collection.deleteMany({ tenant: namespace });

```

Namespace is the string contained in the tenant field.
When running, I get the following error thrown by the package: 

```

error: Error: Command "deleteMany" failed with the following error: More records found to be deleted even after deleting 20 records

```

What do I have to do when there are more than 20 records to delete in a single colllection? Is the approach of separating vectors by metadata key not optimal? If so what should I be doing? 

Thanks

**Comment by toptobes** [comment]
Sorry for the late response (long weekend), but, for the time being, there's unfortunately no way around deleting your records 20-a-time

If speed is a must, you could potentially try firing off many `deleteMany`s concurrently, which I did find in testing to be ~33% faster, firing off a request every 50ms until there was no more deleteMany (of course, YMMV by a lot), but there would be quite a few wasted network calls there

I did find that deleting 1k records 20 at a time (albeit with a really simple schema, your filters may or may not have some adverse effect) didn't take too *obscenely* long, taking ~4.3 seconds for all 1k to be deleted

**Comment by toptobes** [comment]
`deleteMany` is now implicitly paginated in the v1.0.0 release.
