### ISSUE TITLE
`createCollection` is not idempotent

### ISSUE THREAD

**Issue by TejasQ** [datastax/astra-db-ts#27]
Given this code snippet:

<img width="1052" alt="image" src="https://github.com/datastax/astra-db-ts/assets/9947422/745b7b9a-6442-4b31-85e5-2e87ae4a4880">

I get this error:

<img width="885" alt="image" src="https://github.com/datastax/astra-db-ts/assets/9947422/265c2462-0848-4eca-b1c1-e714e643ab12">

My workaround is to actually make it idempotent and _not_ raise an error by wrapping the call to `createCollection` in a try/catch block and swallowing the error. When I do this, everything continues as normal.

**Current status:** calling `createCollection` on an existing collection raises an error when the documentation says it does not.
**Expected:** no error if collection already exists.

There is no difference in configuration.

**Comment by toptobes** [comment]
Apologies, looks like that's somewhat out of date ts-doc—if you pass `checkExists: false`, it should work as expected

e.g.
```ts
const collection = await db.createCollection(collectionName, {
  vector: {
    dimension: 1024,
  },
  checkExists: false,
});
```

It'll be fixed in the next minor version, thanks for bringing this to our attention!

**Comment by toptobes** [comment]
tsdoc tweaked in 1.0.1
